stages:
- deploy

deploy-to-aur:
  stage: deploy
  image: iffregistry.fz-juelich.de/docker-images/gr-build-images/$CI_JOB_NAME
  only:
  - tags@Scientific-IT-Systems/administration/nojava-ipmi-kvm
  script:
  - mkdir --mode=700 ~/.ssh/
  - (umask 0377 && echo "$AUR_PRIVATE_KEY" > ~/.ssh/id_rsa
                && echo "aur.archlinux.org $AUR_HOST_KEY" >> ~/.ssh/known_hosts)
  - for suffix in docker podman; do
      git clone "ssh://aur@aur.archlinux.org/nojava-ipmi-kvm-${suffix}.git" "nojava-ipmi-kvm-${suffix}-aur";
      cd "nojava-ipmi-kvm-${suffix}-aur";
      sed -i -e "/^pkgver=/c\pkgver=\"${CI_COMMIT_TAG#v}\"" -e "/^pkgrel=/c\pkgrel=\"1\"" PKGBUILD;
      (
        source PKGBUILD;
        curl -o source -L "${source[0]}";
        SHA256SUM="$(sha256sum source | awk '{ print $1 }')";
        sed -i "/^sha256sums=/c\sha256sums=(\"${SHA256SUM}\")" PKGBUILD;
      );
      makepkg --printsrcinfo > .SRCINFO;
      git commit -a -m "Update to version ${CI_COMMIT_TAG#v}";
      git push;
      cd ..;
    done
